# Generated by Django 5.2 on 2026-05-30 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='中心名稱')),
                ('addr', models.CharField(blank=True, max_length=200, null=True, verbose_name='中心地址')),
                ('addr_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址描述')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='電話')),
                ('fax', models.CharField(blank=True, max_length=100, null=True, verbose_name='傳真')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='電子郵件')),
                ('map_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='地圖連結')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='中心簡介')),
                ('file_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='檔案狀態')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='建立者')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='建立時間')),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='最後更新者')),
                ('last_updated_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='最後更新時間')),
            ],
            options={
                'verbose_name': '中心',
                'verbose_name_plural': '中心',
                'db_table': 'center',
            },
        ),
        migrations.CreateModel(
            name='CourseMainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='主類別名稱')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='主類別描述')),
                ('file_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='檔案狀態')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='建立者')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='建立時間')),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='最後更新者')),
                ('last_updated_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='最後更新時間')),
            ],
            options={
                'verbose_name': '課程主類別',
                'verbose_name_plural': '課程主類別',
                'db_table': 'course_main_category',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='員工編號')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='名字')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓氏')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='電子郵件')),
                ('addr', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='帳號')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='密碼')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否為管理員')),
                ('file_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='檔案狀態')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='建立者')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='建立時間')),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='最後更新者')),
                ('last_updated_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='最後更新時間')),
            ],
            options={
                'verbose_name': '行政員工',
                'verbose_name_plural': '行政員工',
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='CourseSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='子類別名稱')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='子類別描述')),
                ('file_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='檔案狀態')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='建立者')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='建立時間')),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='最後更新者')),
                ('last_updated_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='最後更新時間')),
                ('main_category', models.ForeignKey(blank=True, db_column='main_category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.coursemaincategory', verbose_name='所屬主類別')),
            ],
            options={
                'verbose_name': '課程子類別',
                'verbose_name_plural': '課程子類別',
                'db_table': 'course_sub_category',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='房間/教室名稱')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('file_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='檔案狀態')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='建立者')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='建立時間')),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='最後更新者')),
                ('last_updated_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='最後更新時間')),
                ('center', models.ForeignKey(blank=True, db_column='center_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.center', verbose_name='所屬中心')),
            ],
            options={
                'verbose_name': '房間/教室',
                'verbose_name_plural': '房間/教室',
                'db_table': 'room',
            },
        ),
    ]
