# Generated by Django 5.2 on 2026-05-30 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='中心名稱'),
        ),
        migrations.AlterField(
            model_name='coursemaincategory',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='主類別名稱'),
        ),
        migrations.AlterField(
            model_name='coursesubcategory',
            name='main_category',
            field=models.ForeignKey(db_column='main_category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.coursemaincategory', verbose_name='所屬主類別'),
        ),
        migrations.AlterField(
            model_name='coursesubcategory',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='子類別名稱'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.CharField(max_length=200, null=True, verbose_name='電子郵件'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='姓氏'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='電話'),
        ),
    ]
