# Generated by Django 5.2 on 2026-05-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_center_name_alter_coursemaincategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='map_url',
            field=models.TextField(blank=True, null=True, verbose_name='地圖連結'),
        ),
    ]
