# Generated by Django 5.2 on 2026-05-30 21:28

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_center_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemaincategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='main_category/icon/'),
        ),
        migrations.AddField(
            model_name='coursemaincategory',
            name='theme_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
