# Generated by Django 5.2 on 2026-05-30 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_coursemaincategory_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesubcategory',
            name='main_category',
        ),
        migrations.DeleteModel(
            name='CourseMainCategory',
        ),
        migrations.DeleteModel(
            name='CourseSubCategory',
        ),
    ]
