# Generated by Django 5.2 on 2026-06-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_coursesubcategory_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
