# Generated by Django 5.2 on 2026-06-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_staff_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='建立者'),
        ),
        migrations.AlterField(
            model_name='center',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立日期時間'),
        ),
        migrations.AlterField(
            model_name='center',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='檔案狀態'),
        ),
        migrations.AlterField(
            model_name='center',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='最後更新者'),
        ),
        migrations.AlterField(
            model_name='center',
            name='last_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新日期時間'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='建立者'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立日期時間'),
        ),
        migrations.AlterField(
            model_name='room',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='檔案狀態'),
        ),
        migrations.AlterField(
            model_name='room',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='最後更新者'),
        ),
        migrations.AlterField(
            model_name='room',
            name='last_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新日期時間'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='建立者'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立日期時間'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='檔案狀態'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='最後更新者'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新日期時間'),
        ),
    ]
