# Generated by Django 5.2 on 2026-06-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=50, unique=True, verbose_name='編號/學號')),
                ('cn_name', models.CharField(max_length=100, verbose_name='中文姓名')),
                ('en_name', models.CharField(max_length=100, verbose_name='英文姓名')),
                ('dob', models.DateTimeField(blank=True, null=True, verbose_name='出生日期')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='電子郵件信箱')),
                ('contact1_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='聯絡人1姓名')),
                ('contact1_relationship', models.CharField(blank=True, max_length=100, null=True, verbose_name='聯絡人1關係')),
                ('contact1_phone', models.CharField(max_length=100, verbose_name='聯絡人1電話')),
                ('contact2_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='聯絡人2姓名')),
                ('contact2_relationship', models.CharField(blank=True, max_length=100, null=True, verbose_name='聯絡人2關係')),
                ('contact2_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='聯絡人2電話')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='登入帳號')),
                ('password', models.CharField(max_length=50, verbose_name='密碼')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用情況')),
                ('register_date', models.DateTimeField(blank=True, null=True, verbose_name='註冊日期')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='帳號效期截止日')),
                ('file_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='存檔狀態')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='建立者')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='建立日期時間')),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='最後更新者')),
                ('last_updated_datetime', models.DateTimeField(auto_now=True, verbose_name='最後更新日期時間')),
            ],
            options={
                'verbose_name': '學員學生基本資料',
                'verbose_name_plural': '學員學生基本資料',
                'db_table': 'student',
                'ordering': ['student_no'],
            },
        ),
    ]
