# Generated by Django 5.2 on 2026-06-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_no'], 'verbose_name': '學生資料', 'verbose_name_plural': '學生資料'},
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='編號'),
        ),
    ]
