# Generated by Django 5.2 on 2026-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['register_date', 'created_datetime'], 'verbose_name': '學生資料', 'verbose_name_plural': '學生資料'},
        ),
        migrations.AlterField(
            model_name='student',
            name='contact1_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='聯絡人1姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact1_relationship',
            field=models.CharField(blank=True, max_length=100, verbose_name='聯絡人1關係'),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact2_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='聯絡人2姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact2_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='聯絡人2電話'),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact2_relationship',
            field=models.CharField(blank=True, max_length=100, verbose_name='聯絡人2關係'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='建立者'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateTimeField(blank=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='expiry_date',
            field=models.DateTimeField(blank=True, verbose_name='帳號效期截止日'),
        ),
        migrations.AlterField(
            model_name='student',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='存檔狀態'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='最後更新者'),
        ),
        migrations.AlterField(
            model_name='student',
            name='register_date',
            field=models.DateTimeField(blank=True, verbose_name='註冊日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='備註'),
        ),
    ]
