# Generated by Django 5.2 on 2026-06-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='帳號效期截止日'),
        ),
    ]
