# Generated by Django 5.2 on 2026-06-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Email是否已驗證?'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用?'),
        ),
    ]
