# Generated by Django 5.2 on 2026-06-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='檔案狀態'),
        ),
    ]
