# Generated by Django 5.2 on 2026-05-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='導師編號')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='稱謂/職稱')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='名字')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓氏')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='電子郵件')),
                ('addr', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('dob', models.DateTimeField(blank=True, null=True, verbose_name='出生日期')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='帳號')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='密碼')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('file_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='檔案狀態')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='建立者')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='建立時間')),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='最後更新者')),
                ('last_updated_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='最後更新時間')),
            ],
            options={
                'verbose_name': '導師',
                'verbose_name_plural': '導師',
                'db_table': 'teacher',
            },
        ),
    ]
