# Generated by Django 5.2 on 2026-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_email_alter_teacher_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='addr',
            field=models.CharField(blank=True, max_length=200, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='建立者'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dob',
            field=models.DateTimeField(blank=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=200, verbose_name='電子郵件'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='檔案狀態'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='姓氏'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='最後更新者'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新時間'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(blank=True, max_length=50, verbose_name='密碼'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='導師編號'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='稱謂/職稱'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(blank=True, max_length=50, verbose_name='帳號'),
        ),
    ]
