# Generated by Django 5.2 on 2026-06-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_addr_alter_teacher_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='dob',
            field=models.DateField(blank=True, verbose_name='出生日期'),
        ),
    ]
