# Generated by Django 5.2 on 2026-05-30 21:37

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='主類別名稱')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='主類別描述')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='main_category/icon/')),
                ('theme_color', colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=25, null=True, samples=None)),
                ('file_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='檔案狀態')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='建立者')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='建立時間')),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='最後更新者')),
                ('last_updated_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='最後更新時間')),
            ],
            options={
                'verbose_name': '課程主類別',
                'verbose_name_plural': '課程主類別',
                'db_table': 'course_main_category',
            },
        ),
        migrations.CreateModel(
            name='CourseSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='子類別名稱')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='子類別描述')),
                ('file_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='檔案狀態')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='建立者')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='建立時間')),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='最後更新者')),
                ('last_updated_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='最後更新時間')),
                ('main_category', models.ForeignKey(db_column='main_category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursemaincategory', verbose_name='所屬主類別')),
            ],
            options={
                'verbose_name': '課程子類別',
                'verbose_name_plural': '課程子類別',
                'db_table': 'course_sub_category',
            },
        ),
    ]
