# Generated by Django 5.2 on 2026-05-30 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubcategory',
            name='main_category',
            field=models.ForeignKey(db_column='main_category_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.coursemaincategory', verbose_name='所屬主類別'),
            preserve_default=False,
        ),
    ]
