# Generated by Django 5.2 on 2026-05-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coursesubcategory_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemaincategory',
            name='short_name',
            field=models.CharField(max_length=50, null=True, verbose_name='簡稱'),
        ),
        migrations.AddField(
            model_name='coursesubcategory',
            name='short_name',
            field=models.CharField(max_length=50, null=True, verbose_name='簡稱'),
        ),
        migrations.AlterField(
            model_name='coursemaincategory',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='coursesubcategory',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
