# Generated by Django 5.2 on 2026-05-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursemaincategory_short_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemaincategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='coursemaincategory',
            name='icon_class',
            field=models.CharField(blank=True, help_text='例如: fa-baby', max_length=100, null=True, verbose_name='Icon(FontAwesome Icon Class)'),
        ),
    ]
