# Generated by Django 5.2 on 2026-06-01 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_coursesubcategory_main_category_and_more'),
        ('courses', '0004_remove_coursemaincategory_icon_and_more'),
        ('teachers', '0002_alter_teacher_email_alter_teacher_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemaincategory',
            old_name='icon_class',
            new_name='nav_icon',
        ),
        migrations.AddField(
            model_name='coursemaincategory',
            name='home_photo',
            field=models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d/', verbose_name='首頁展示圖片'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='例如：PY-2026-001', max_length=50, verbose_name='課程編號')),
                ('name', models.CharField(max_length=50, verbose_name='課程名稱')),
                ('content', models.TextField(blank=True, null=True, verbose_name='課程介紹')),
                ('feature_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='詳情 1')),
                ('feature_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='詳情 2')),
                ('feature_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='詳情 3')),
                ('feature_4', models.CharField(blank=True, max_length=200, null=True, verbose_name='詳情 4')),
                ('feature_5', models.CharField(blank=True, max_length=200, null=True, verbose_name='詳情 5')),
                ('feature_6', models.CharField(blank=True, max_length=200, null=True, verbose_name='詳情 6')),
                ('feature_7', models.CharField(blank=True, max_length=200, null=True, verbose_name='詳情 7')),
                ('feature_8', models.CharField(blank=True, max_length=200, null=True, verbose_name='詳情 8')),
                ('total_lessons', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='總上課堂數')),
                ('hours_per_lesson', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='每堂上課時數')),
                ('period_from', models.DateField(verbose_name='開始日期')),
                ('period_to', models.DateField(verbose_name='結束日期')),
                ('time_from', models.TimeField(blank=True, help_text='格式如 14:00', null=True, verbose_name='上課開始時間')),
                ('time_to', models.TimeField(blank=True, help_text='格式如 16:00', null=True, verbose_name='上課結束時間')),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='實際實體學費')),
                ('course_status', models.CharField(choices=[('招生中', '招生中'), ('已取消', '已取消'), ('已額滿', '已額滿'), ('進行中', '進行中'), ('已完結', '已完結')], default='', max_length=50, verbose_name='課程狀態')),
                ('registation_expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='報名截止截止時間')),
                ('max_no_student', models.IntegerField(verbose_name='人數上限限制')),
                ('is_promote', models.BooleanField(default=False, help_text='控制是否在外台首頁焦點推薦區塊顯示', verbose_name='是否熱門推薦')),
                ('file_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='存檔狀態')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='建立者')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='建立日期時間')),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='最後更新者')),
                ('last_updated_datetime', models.DateTimeField(auto_now=True, verbose_name='最後更新日期時間')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='administration.center', verbose_name='上課分校/中心')),
                ('default_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='administration.room', verbose_name='預設上課教室')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='courses.coursesubcategory', verbose_name='課程子分類')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='teachers.teacher', verbose_name='任課老師')),
            ],
            options={
                'verbose_name': '實體班級課程',
                'verbose_name_plural': '實體班級課程',
                'db_table': 'course',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(help_text='1=星期一, 2=星期二, ..., 7=星期日', verbose_name='星期幾數字鍵')),
                ('start_time', models.TimeField(verbose_name='該日上課開始時間')),
                ('end_time', models.TimeField(verbose_name='該日上課結束時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course', verbose_name='關聯實體課程')),
            ],
            options={
                'verbose_name': '課程內部拆解規律排班',
                'verbose_name_plural': '課程內部拆解規律排班',
                'db_table': 'course_schedule',
                'ordering': ['course', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CourseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(blank=True, help_text='原系統對應分類之流水號', null=True, verbose_name='分類 ID參考')),
                ('name', models.CharField(max_length=50, verbose_name='範本課程名稱')),
                ('course_content', models.TextField(blank=True, null=True, verbose_name='課程內容大綱')),
                ('feature_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='特徵 1')),
                ('feature_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='特徵 2')),
                ('feature_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='特徵 3')),
                ('feature_4', models.CharField(blank=True, max_length=200, null=True, verbose_name='特徵 4')),
                ('feature_5', models.CharField(blank=True, max_length=200, null=True, verbose_name='特徵 5')),
                ('feature_6', models.CharField(blank=True, max_length=200, null=True, verbose_name='特徵 6')),
                ('feature_7', models.CharField(blank=True, max_length=200, null=True, verbose_name='特徵 7')),
                ('feature_8', models.CharField(blank=True, max_length=200, null=True, verbose_name='特徵 8')),
                ('total_lessons', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='總堂數')),
                ('hours_per_lesson', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='每堂時數')),
                ('total_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='總時數')),
                ('course_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='預設學費')),
                ('is_active', models.BooleanField(default=True, help_text='控制此範本是否可在開課時被選用', verbose_name='是否啟用')),
                ('file_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='存檔狀態')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='建立者')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='建立日期時間')),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='最後更新者')),
                ('last_updated_datetime', models.DateTimeField(auto_now=True, verbose_name='最後更新日期時間')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='templates', to='teachers.teacher', verbose_name='負責/授課老師')),
            ],
            options={
                'verbose_name': '課程基本範本',
                'verbose_name_plural': '課程基本範本',
                'db_table': 'course_template',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='courses.coursetemplate', verbose_name='關聯課程範本'),
        ),
    ]
