# Generated by Django 5.2 on 2026-06-01 05:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_coursesubcategory_main_category_and_more'),
        ('courses', '0005_rename_icon_class_coursemaincategory_nav_icon_and_more'),
        ('teachers', '0002_alter_teacher_email_alter_teacher_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetemplate',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='coursetemplate',
            name='course_content',
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='建立者'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立日期時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='存檔狀態'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='最後更新者'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='last_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新日期時間'),
        ),
        migrations.AddField(
            model_name='coursetemplate',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='課程介紹'),
        ),
        migrations.AddField(
            model_name='coursetemplate',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.coursesubcategory', verbose_name='課程子分類'),
        ),
        migrations.AlterField(
            model_name='course',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administration.center', verbose_name='上課分校/中心'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('草稿', '草稿'), ('招生中', '招生中'), ('已取消', '已取消'), ('已額滿', '已額滿'), ('進行中', '進行中'), ('已完結', '已完結')], default='', max_length=50, verbose_name='課程狀態'),
        ),
        migrations.AlterField(
            model_name='course',
            name='default_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.room', verbose_name='預設上課教室'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.coursesubcategory', verbose_name='課程子分類'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.teacher', verbose_name='任課老師'),
        ),
        migrations.AlterField(
            model_name='course',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.coursetemplate', verbose_name='關聯課程範本'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='name',
            field=models.CharField(max_length=50, verbose_name='課程名稱'),
        ),
    ]
