# Generated by Django 5.2 on 2026-06-01 14:11

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_coursetemplate_category_id_and_more'),
        ('teachers', '0002_alter_teacher_email_alter_teacher_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-id'], 'verbose_name': '課程', 'verbose_name_plural': '課程'},
        ),
        migrations.AlterModelOptions(
            name='courseschedule',
            options={'ordering': ['course', 'day_of_week', 'start_time'], 'verbose_name': '課程排班表', 'verbose_name_plural': '課程排班表'},
        ),
        migrations.AlterModelOptions(
            name='coursetemplate',
            options={'ordering': ['-id'], 'verbose_name': '課程範本', 'verbose_name_plural': '課程範本'},
        ),
        migrations.AddField(
            model_name='course',
            name='is_web_publish',
            field=models.BooleanField(default=False, verbose_name='是否公開發布?'),
        ),
        migrations.AddField(
            model_name='coursemaincategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否可在用/顯示', verbose_name='是否啟用'),
        ),
        migrations.AddField(
            model_name='coursesubcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否可在用/顯示', verbose_name='是否啟用'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='學費'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('created', 'created'), ('end', 'end'), ('cancel', 'cancel')], default='', max_length=50, verbose_name='課程狀態'),
        ),
        migrations.AlterField(
            model_name='course',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_promote',
            field=models.BooleanField(default=False, verbose_name='是是否在首頁推薦?'),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_no_student',
            field=models.IntegerField(verbose_name='人數上限'),
        ),
        migrations.AlterField(
            model_name='course',
            name='registation_expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='截止時間'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.coursesubcategory', verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.teacher', verbose_name='老師'),
        ),
        migrations.AlterField(
            model_name='course',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.coursetemplate', verbose_name='範本'),
        ),
        migrations.AlterField(
            model_name='coursemaincategory',
            name='theme_color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course', verbose_name='課程'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='day_of_week',
            field=models.IntegerField(help_text='1=星期一, 2=星期二, ..., 7=星期日', verbose_name='毎星期'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='end_time',
            field=models.TimeField(verbose_name='結束時間'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='start_time',
            field=models.TimeField(verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.coursesubcategory', verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='templates', to='teachers.teacher', verbose_name='老師'),
        ),
    ]
