# Generated by Django 5.2 on 2026-06-01 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_options_alter_courseschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.coursetemplate', verbose_name='範本'),
        ),
    ]
