# Generated by Django 5.2 on 2026-06-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='course/%Y/%m/%d/', verbose_name='首頁展示圖片'),
        ),
        migrations.AlterField(
            model_name='coursemaincategory',
            name='home_photo',
            field=models.ImageField(blank=True, null=True, upload_to='main_category/%Y/%m/%d/', verbose_name='首頁展示圖片'),
        ),
    ]
