# Generated by Django 5.2 on 2026-06-02 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_coursesubcategory_main_category_and_more'),
        ('courses', '0009_course_photo_alter_coursemaincategory_home_photo'),
        ('students', '0002_alter_student_options_alter_student_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='狀態')),
                ('sign_up_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='報名日期')),
                ('reject_date', models.DateTimeField(blank=True, null=True, verbose_name='拒絕時間')),
                ('reject_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='拒絕原因')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='付款時間')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='付款金額')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='付款方式')),
                ('payment_ref', models.CharField(max_length=50, verbose_name='付款參考編號')),
                ('payment_remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='付款備註')),
                ('file_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='檔案狀態')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='建立者')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='建立日期時間')),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='最後更新者')),
                ('last_updated_datetime', models.DateTimeField(auto_now=True, verbose_name='最後更新日期時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='signup_set', to='courses.course', verbose_name='課程')),
                ('reject_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rejected_signups', to='administration.staff', verbose_name='拒絕者')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='signups', to='students.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '課程報名',
                'verbose_name_plural': '課程報名',
                'db_table': 'sign_up',
                'ordering': ['-id'],
            },
        ),
    ]
