# Generated by Django 5.2 on 2026-06-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=50, verbose_name='付款參考編號'),
        ),
    ]
