# Generated by Django 5.2 on 2026-06-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_signup_payment_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='age_group',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='對象'),
        ),
        migrations.AddField(
            model_name='course',
            name='lesson_weekday_pattern',
            field=models.CharField(blank=True, help_text='格式如 逢星期六', max_length=200, null=True, verbose_name='課程日期安排模式'),
        ),
    ]
