# Generated by Django 5.2 on 2026-06-02 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_coursesubcategory_main_category_and_more'),
        ('courses', '0012_course_age_group_course_lesson_weekday_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_reject',
            field=models.BooleanField(default=False, verbose_name='審核:拒絕報名'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='reject_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.staff', verbose_name='拒絕者'),
        ),
    ]
