# Generated by Django 5.2 on 2026-06-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_coursesubcategory_main_category_and_more'),
        ('courses', '0013_signup_is_reject_alter_signup_reject_by'),
        ('teachers', '0003_alter_teacher_addr_alter_teacher_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemaincategory',
            name='list_photo',
            field=models.ImageField(blank=True, null=True, upload_to='sub_category/%Y/%m/%d/', verbose_name='課程列表圖片'),
        ),
        migrations.AddField(
            model_name='coursesubcategory',
            name='list_photo',
            field=models.ImageField(blank=True, upload_to='sub_category/%Y/%m/%d/', verbose_name='課程列表圖片'),
        ),
        migrations.AlterField(
            model_name='course',
            name='age_group',
            field=models.CharField(blank=True, max_length=200, verbose_name='對象'),
        ),
        migrations.AlterField(
            model_name='course',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.center', verbose_name='上課分校/中心'),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(blank=True, verbose_name='課程介紹'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='建立者'),
        ),
        migrations.AlterField(
            model_name='course',
            name='feature_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='詳情 1'),
        ),
        migrations.AlterField(
            model_name='course',
            name='feature_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='詳情 2'),
        ),
        migrations.AlterField(
            model_name='course',
            name='feature_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='詳情 3'),
        ),
        migrations.AlterField(
            model_name='course',
            name='feature_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='詳情 4'),
        ),
        migrations.AlterField(
            model_name='course',
            name='feature_5',
            field=models.CharField(blank=True, max_length=200, verbose_name='詳情 5'),
        ),
        migrations.AlterField(
            model_name='course',
            name='feature_6',
            field=models.CharField(blank=True, max_length=200, verbose_name='詳情 6'),
        ),
        migrations.AlterField(
            model_name='course',
            name='feature_7',
            field=models.CharField(blank=True, max_length=200, verbose_name='詳情 7'),
        ),
        migrations.AlterField(
            model_name='course',
            name='feature_8',
            field=models.CharField(blank=True, max_length=200, verbose_name='詳情 8'),
        ),
        migrations.AlterField(
            model_name='course',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hours_per_lesson',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='每堂上課時數'),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='最後更新者'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lesson_weekday_pattern',
            field=models.CharField(blank=True, help_text='格式如 逢星期六', max_length=200, verbose_name='課程日期安排模式'),
        ),
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, upload_to='course/%Y/%m/%d/', verbose_name='首頁展示圖片'),
        ),
        migrations.AlterField(
            model_name='course',
            name='registation_expiry_date',
            field=models.DateTimeField(blank=True, verbose_name='截止時間'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.coursesubcategory', verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.teacher', verbose_name='老師'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_from',
            field=models.TimeField(blank=True, help_text='格式如 14:00', verbose_name='上課開始時間'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_to',
            field=models.TimeField(blank=True, help_text='格式如 16:00', verbose_name='上課結束時間'),
        ),
        migrations.AlterField(
            model_name='coursemaincategory',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='建立者'),
        ),
        migrations.AlterField(
            model_name='coursemaincategory',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='coursemaincategory',
            name='desc',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='coursemaincategory',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='檔案狀態'),
        ),
        migrations.AlterField(
            model_name='coursemaincategory',
            name='home_photo',
            field=models.ImageField(blank=True, null=True, upload_to='main_category/%Y/%m/%d/', verbose_name='首頁圖片'),
        ),
        migrations.AlterField(
            model_name='coursemaincategory',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='最後更新者'),
        ),
        migrations.AlterField(
            model_name='coursemaincategory',
            name='last_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新時間'),
        ),
        migrations.AlterField(
            model_name='coursemaincategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='主類別名稱'),
        ),
        migrations.AlterField(
            model_name='coursemaincategory',
            name='short_name',
            field=models.CharField(max_length=50, verbose_name='簡稱'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='建立者'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='存檔狀態'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='最後更新者'),
        ),
        migrations.AlterField(
            model_name='coursesubcategory',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='建立者'),
        ),
        migrations.AlterField(
            model_name='coursesubcategory',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='coursesubcategory',
            name='desc',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='coursesubcategory',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='檔案狀態'),
        ),
        migrations.AlterField(
            model_name='coursesubcategory',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='最後更新者'),
        ),
        migrations.AlterField(
            model_name='coursesubcategory',
            name='last_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新時間'),
        ),
        migrations.AlterField(
            model_name='coursesubcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='子類別名稱'),
        ),
        migrations.AlterField(
            model_name='coursesubcategory',
            name='short_name',
            field=models.CharField(max_length=50, verbose_name='簡稱'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='content',
            field=models.TextField(blank=True, verbose_name='課程介紹'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='course_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='預設學費'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='建立者'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='feature_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='特徵 1'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='feature_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='特徵 2'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='feature_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='特徵 3'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='feature_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='特徵 4'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='feature_5',
            field=models.CharField(blank=True, max_length=200, verbose_name='特徵 5'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='feature_6',
            field=models.CharField(blank=True, max_length=200, verbose_name='特徵 6'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='feature_7',
            field=models.CharField(blank=True, max_length=200, verbose_name='特徵 7'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='feature_8',
            field=models.CharField(blank=True, max_length=200, verbose_name='特徵 8'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='hours_per_lesson',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='每堂時數'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='最後更新者'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='sub_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.coursesubcategory', verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='templates', to='teachers.teacher', verbose_name='老師'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='總時數'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='total_lessons',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='總堂數'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='建立者'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='檔案狀態'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='最後更新者'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='付款金額'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='payment_date',
            field=models.DateTimeField(blank=True, verbose_name='付款時間'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='payment_remarks',
            field=models.CharField(blank=True, max_length=200, verbose_name='付款備註'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='reject_date',
            field=models.DateTimeField(blank=True, verbose_name='拒絕時間'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='拒絕原因'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='sign_up_date',
            field=models.CharField(blank=True, max_length=50, verbose_name='報名日期'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='狀態'),
        ),
    ]
