# Generated by Django 5.2 on 2026-06-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_coursemaincategory_list_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='online_payment_intent',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe payment intent'),
        ),
        migrations.AddField(
            model_name='signup',
            name='online_payment_session',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Session'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=255, verbose_name='付款參考'),
        ),
    ]
