# Generated by Django 5.2 on 2026-06-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_signup_online_payment_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='reject_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='拒絕時間'),
        ),
    ]
