# Generated by Django 5.2 on 2026-06-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_signup_reject_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('created', 'created'), ('cancel', 'cancel')], default='', max_length=50, verbose_name='課程狀態'),
        ),
    ]
