# Generated by Django 5.2 on 2026-06-07 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_alter_center_created_by_and_more'),
        ('courses', '0017_alter_course_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='is_reject',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='online_payment_intent',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='reject_by',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='reject_date',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='reject_reason',
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='lesson_content',
            field=models.TextField(blank=True, verbose_name='課堂內容'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='lesson_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='課堂標題'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='signup',
            name='cancel_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.staff', verbose_name='取消者'),
        ),
        migrations.AddField(
            model_name='signup',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消時間'),
        ),
        migrations.AddField(
            model_name='signup',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='取消原因'),
        ),
        migrations.AlterField(
            model_name='course',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='檔案狀態'),
        ),
        migrations.AlterField(
            model_name='coursemaincategory',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立日期時間'),
        ),
        migrations.AlterField(
            model_name='coursemaincategory',
            name='last_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新日期時間'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='檔案狀態'),
        ),
        migrations.AlterField(
            model_name='coursesubcategory',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立日期時間'),
        ),
        migrations.AlterField(
            model_name='coursesubcategory',
            name='last_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新日期時間'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='檔案狀態'),
        ),
        migrations.CreateModel(
            name='SignUpRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_status', models.CharField(blank=True, max_length=100, verbose_name='檔案狀態')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='建立者')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='建立日期時間')),
                ('last_updated_by', models.CharField(blank=True, max_length=100, verbose_name='最後更新者')),
                ('last_updated_datetime', models.DateTimeField(auto_now=True, verbose_name='最後更新日期時間')),
                ('refund_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='退款日期')),
                ('refund_method', models.CharField(blank=True, max_length=100, verbose_name='退款方式')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='退款金額')),
                ('refund_ref', models.CharField(blank=True, max_length=255, verbose_name='退款參考')),
                ('refund_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.staff', verbose_name='處理人')),
                ('sign_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='courses.signup', verbose_name='報名紀錄')),
            ],
            options={
                'verbose_name': '報名退款',
                'verbose_name_plural': '報名退款',
                'db_table': 'sign_up_refund',
                'ordering': ['-id'],
            },
        ),
    ]
