# Generated by Django 5.2 on 2026-06-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_signup_is_reject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='status',
            new_name='sign_up_status',
        ),
    ]
