# Generated by Django 5.2 on 2026-06-07 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_rename_status_signup_sign_up_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='付款時間'),
        ),
    ]
