# Generated by Django 5.2 on 2026-06-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_signup_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_lessons',
            field=models.IntegerField(verbose_name='總上課堂數'),
        ),
    ]
