# Generated by Django 5.2 on 2026-05-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='標題')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='發布日期')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='到期日期')),
                ('is_publish', models.BooleanField(default=True, verbose_name='是否發布')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='內文描述')),
                ('list_photo', models.CharField(blank=True, max_length=100, null=True, verbose_name='列表圖片路徑')),
                ('photo_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='圖片 1 路徑')),
                ('photo_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='圖片 2 路徑')),
                ('photo_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='圖片 3 路徑')),
                ('file_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='檔案狀態')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='建立者')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='建立時間')),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='最後更新者')),
                ('last_updated_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='最後更新時間')),
            ],
            options={
                'verbose_name': '最新消息',
                'verbose_name_plural': '最新消息',
                'db_table': 'news',
            },
        ),
    ]
