# Generated by Django 5.2 on 2026-05-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='是否發布'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='標題'),
        ),
    ]
