# Generated by Django 5.2 on 2026-05-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_contents', '0002_alter_news_is_publish_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d/'),
        ),
    ]
