# Generated by Django 5.2 on 2026-06-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_contents', '0003_alter_news_photo_1_alter_news_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='list_photo',
            field=models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d/', verbose_name='列表展示圖片'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d/', verbose_name='圖片1'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d/', verbose_name='圖片2'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d/', verbose_name='圖片3'),
        ),
    ]
