# Generated by Django 5.2 on 2026-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_contents', '0004_alter_news_list_photo_alter_news_photo_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='建立者'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.TextField(blank=True, verbose_name='內文描述'),
        ),
        migrations.AlterField(
            model_name='news',
            name='expiry_date',
            field=models.DateTimeField(blank=True, verbose_name='到期日期'),
        ),
        migrations.AlterField(
            model_name='news',
            name='file_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='檔案狀態'),
        ),
        migrations.AlterField(
            model_name='news',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='最後更新者'),
        ),
        migrations.AlterField(
            model_name='news',
            name='last_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新時間'),
        ),
        migrations.AlterField(
            model_name='news',
            name='list_photo',
            field=models.ImageField(blank=True, upload_to='news/%Y/%m/%d/', verbose_name='列表展示圖片'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='news/%Y/%m/%d/', verbose_name='圖片1'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='news/%Y/%m/%d/', verbose_name='圖片2'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='news/%Y/%m/%d/', verbose_name='圖片3'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_date',
            field=models.DateTimeField(verbose_name='發布日期'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='標題'),
        ),
    ]
