# Generated by Django 5.2 on 2026-06-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_contents', '0005_alter_news_created_by_alter_news_created_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立日期時間'),
        ),
        migrations.AlterField(
            model_name='news',
            name='last_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新日期時間'),
        ),
    ]
